export const USER_ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  SALES_REP: 'SALES_REP',
  SALES_MANAGER: 'SALES_MANAGER',
  FINANCE_OPERATIONS: 'FINANCE_OPERATIONS',
})

export const REQUESTABLE_ROLES = Object.freeze([
  USER_ROLES.SALES_REP,
  USER_ROLES.SALES_MANAGER,
  USER_ROLES.FINANCE_OPERATIONS,
])

export const USER_STATUSES = Object.freeze({
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
})

export const SESSION_KINDS = Object.freeze({
  INTERNAL: 'INTERNAL',
  CUSTOMER_PORTAL: 'CUSTOMER_PORTAL',
})
