import {
  SESSION_KINDS,
  USER_ROLES,
  USER_STATUSES,
} from '@app/models/constants'

export { SESSION_KINDS, USER_ROLES, USER_STATUSES }

export const REQUESTABLE_ROLES = Object.freeze([
  USER_ROLES.SALES_REP,
  USER_ROLES.MANAGER,
  USER_ROLES.FINANCE,
  USER_ROLES.CUSTOMER,
])
